# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' define optimization function
#' @export
optimMMTC <- function(Y, upsilon, ThetaX, K, A, etainit, iter = 2000L, eigvalthresh = -0.001, numexcessthresh = 0L, calcGradHess = TRUE) {
    .Call('_mongrel_optimMMTC', PACKAGE = 'mongrel', Y, upsilon, ThetaX, K, A, etainit, iter, eigvalthresh, numexcessthresh, calcGradHess)
}

#' @export
uncollapseMMTC <- function(eta, X, Theta, Gamma, Xi, upsilon) {
    .Call('_mongrel_uncollapseMMTC', PACKAGE = 'mongrel', eta, X, Theta, Gamma, Xi, upsilon)
}

#' @export
rMatNormalCholesky_test <- function(M, LU, LV) {
    .Call('_mongrel_rMatNormalCholesky_test', PACKAGE = 'mongrel', M, LU, LV)
}

#' @export
rInvWishCholesky_test <- function(v, Psi) {
    .Call('_mongrel_rInvWishCholesky_test', PACKAGE = 'mongrel', v, Psi)
}

#' @export
rMatUnitNormal_test <- function(n, m) {
    .Call('_mongrel_rMatUnitNormal_test', PACKAGE = 'mongrel', n, m)
}

